### ISSUE TITLE
Rate Bug

### ISSUE THREAD

**Issue by BlissGD** [xXFireBlastXx/GDPS-Updates#1]
El servidor tiene un Bug que al ratear como usuario normal y sales y luego actualizas para ver el nivel sigue disponible para seguir rateandolo, osea, como el antiguo glitch para los 100 Likes.

**Comment by xXFireBlastXx** [comment]
Para usuarios no-mod (Sin moderador) podran dar rate a cualquier nivel infinitamente, igualmente los moderadores, eso no afecta en nada al funcionamiento del Servidor. Gracias Por tu Bug! :D

**Comment by BlissGD** [comment]
Gracias uwu
